modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/MC-U-Team/Voice-Chat/issues"
displayURL="https://u-team.info/mods/voicechat"
logoFile="logo.png"
license="Apache 2.0"
credits="Team U-Team"
authors="HyCraftHD"

[[mods]]
	modId="voicechat"
	version="${file.jarVersion}"
	displayName="Voice Chat"
	updateJSONURL="https://api.u-team.info/update/voicechat.json"
	description="This mod adds a simple voice chat to minecraft. Use it with the music player mod to stream your music to your friends"
	
	[[dependencies.voicechat]]
	    modId="forge"
	    mandatory=true
	    versionRange="[36.1.12,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.voicechat]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.16.5]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.voicechat]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[3.2.1.195,)"
	    ordering="NONE"
	    side="BOTH"